#!/usr/bin/env python3
"""
Generate scripts/step0_gps_staging.sql from scripts/gps_review.csv
"""

import csv
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH   = os.path.join(SCRIPT_DIR, 'gps_review.csv')
SQL_PATH   = os.path.join(SCRIPT_DIR, 'step0_gps_staging.sql')


def esc(value: str) -> str:
    """Escape a string value for SQL single-quoted literals."""
    if value is None or value == '':
        return 'NULL'
    return "'" + value.replace("'", "''") + "'"


def main():
    rows = []
    with open(CSV_PATH, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    lines = []
    lines.append('-- ============================================================')
    lines.append('-- NotoTrack: Step 0 – GPS Staging Table + Seed Data')
    lines.append('-- Run in Supabase SQL editor BEFORE running step1_migration.sql')
    lines.append('-- Generated by scripts/generate_gps_staging_sql.py')
    lines.append('-- ============================================================')
    lines.append('')

    # ── 1. Create table ──────────────────────────────────────────────────────
    lines.append('-- ── 1. Create gps_staging table ─────────────────────────────────')
    lines.append('')
    lines.append('CREATE TABLE IF NOT EXISTS public.gps_staging (')
    lines.append('  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),')
    lines.append('  lat              DECIMAL(10,8) NOT NULL,')
    lines.append('  lng              DECIMAL(11,8) NOT NULL,')
    lines.append('  shop_hint        TEXT,')
    lines.append('  ward_hint        TEXT,')
    lines.append('  municipality_hint TEXT,')
    lines.append('  raw_context      TEXT,')
    lines.append('  match_score      DECIMAL(4,2),')
    lines.append('  auto_matched     BOOLEAN DEFAULT FALSE,')
    lines.append('  assigned_to      UUID REFERENCES public.assessments(id),')
    lines.append('  assigned_at      TIMESTAMPTZ,')
    lines.append('  created_at       TIMESTAMPTZ DEFAULT now()')
    lines.append(');')
    lines.append('')

    # ── 2. Enable RLS ─────────────────────────────────────────────────────────
    lines.append('-- ── 2. Enable RLS ────────────────────────────────────────────────')
    lines.append('')
    lines.append('ALTER TABLE public.gps_staging ENABLE ROW LEVEL SECURITY;')
    lines.append('')

    # ── 3. RLS policies ───────────────────────────────────────────────────────
    lines.append('-- ── 3. RLS policies ──────────────────────────────────────────────')
    lines.append('')
    lines.append('-- Authenticated users can read staging pins')
    lines.append('DROP POLICY IF EXISTS "authenticated_select_gps_staging" ON public.gps_staging;')
    lines.append('CREATE POLICY "authenticated_select_gps_staging"')
    lines.append('  ON public.gps_staging')
    lines.append('  FOR SELECT')
    lines.append('  USING (auth.role() = \'authenticated\');')
    lines.append('')
    lines.append('-- Coordinators (role_tier <= 2) can update staging pins')
    lines.append('-- Using permissive policy for now')
    lines.append('DROP POLICY IF EXISTS "coordinators_update_gps_staging" ON public.gps_staging;')
    lines.append('CREATE POLICY "coordinators_update_gps_staging"')
    lines.append('  ON public.gps_staging')
    lines.append('  FOR UPDATE')
    lines.append('  USING (true)')
    lines.append('  WITH CHECK (true);')
    lines.append('')

    # ── 4. Seed data ──────────────────────────────────────────────────────────
    lines.append('-- ── 4. Seed 138 GPS rows from gps_review.csv ────────────────────')
    lines.append('')
    lines.append('INSERT INTO public.gps_staging')
    lines.append('  (lat, lng, shop_hint, ward_hint, municipality_hint, raw_context, match_score, auto_matched)')
    lines.append('VALUES')

    value_parts = []
    for row in rows:
        lat   = float(row['lat'])
        lng   = float(row['lng'])

        shop_hint         = esc(row.get('chat_hint', ''))
        ward_hint         = esc(row.get('ward_hint', ''))
        municipality_hint = esc(row.get('municipality_hint', ''))
        raw_context       = esc(row.get('raw_context', ''))

        score_raw = row.get('match_score', '')
        try:
            match_score = f"{float(score_raw):.2f}"
        except (ValueError, TypeError):
            match_score = 'NULL'

        auto_raw     = row.get('auto_applied', '').strip().upper()
        auto_matched = 'TRUE' if auto_raw == 'YES' else 'FALSE'

        value_parts.append(
            f"  ({lat}, {lng}, {shop_hint}, {ward_hint}, {municipality_hint}, "
            f"{raw_context}, {match_score}, {auto_matched})"
        )

    lines.append(',\n'.join(value_parts))
    lines.append('ON CONFLICT DO NOTHING;')
    lines.append('')
    lines.append('-- ── Done ─────────────────────────────────────────────────────────')
    lines.append(f'-- {len(rows)} rows seeded from gps_review.csv')
    lines.append('-- ============================================================')
    lines.append('')

    sql = '\n'.join(lines)
    with open(SQL_PATH, 'w', encoding='utf-8') as f:
        f.write(sql)

    print(f"Written {len(rows)} rows to {SQL_PATH}")


if __name__ == '__main__':
    main()
