-- ============================================================
-- NotoTrack: Step 0 – GPS Staging Table + Seed Data
-- Run in Supabase SQL editor BEFORE running step1_migration.sql
-- Generated by scripts/generate_gps_staging_sql.py
-- ============================================================

-- ── 1. Create gps_staging table ─────────────────────────────────

CREATE TABLE IF NOT EXISTS public.gps_staging (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lat              DECIMAL(10,8) NOT NULL,
  lng              DECIMAL(11,8) NOT NULL,
  shop_hint        TEXT,
  ward_hint        TEXT,
  municipality_hint TEXT,
  raw_context      TEXT,
  match_score      DECIMAL(4,2),
  auto_matched     BOOLEAN DEFAULT FALSE,
  assigned_to      UUID REFERENCES public.assessments(id),
  assigned_at      TIMESTAMPTZ,
  created_at       TIMESTAMPTZ DEFAULT now()
);

-- ── 2. Enable RLS ────────────────────────────────────────────────

ALTER TABLE public.gps_staging ENABLE ROW LEVEL SECURITY;

-- ── 3. RLS policies ──────────────────────────────────────────────

-- Authenticated users can read staging pins
DROP POLICY IF EXISTS "authenticated_select_gps_staging" ON public.gps_staging;
CREATE POLICY "authenticated_select_gps_staging"
  ON public.gps_staging
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Coordinators (role_tier <= 2) can update staging pins
-- Using permissive policy for now
DROP POLICY IF EXISTS "coordinators_update_gps_staging" ON public.gps_staging;
CREATE POLICY "coordinators_update_gps_staging"
  ON public.gps_staging
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- ── 4. Seed 138 GPS rows from gps_review.csv ────────────────────

INSERT INTO public.gps_staging
  (lat, lng, shop_hint, ward_hint, municipality_hint, raw_context, match_score, auto_matched)
VALUES
  (-29.211189, 31.151531, 'Kwa Jim supermarket', NULL, NULL, 'Kwa Jim supermarket (iLembe, iLembe District Municipality, ZA): https://maps.google.com/?q=-29.211189,31.151531', 0.92, TRUE),
  (-29.528112, 30.94734, 'Gasela Primary School', NULL, NULL, 'Gasela Primary School (iLembe District Municipality, ZA): https://maps.google.com/?q=-29.528112,30.947340', 0.80, TRUE),
  (-29.588116, 30.851511, 'Kwamwema', NULL, NULL, 'Kwamwema (Ndwedwe Local Municipality, ZA): https://maps.google.com/?q=-29.588116,30.851511', 0.75, TRUE),
  (-29.534163, 30.863337, 'Tafamasi', NULL, NULL, 'Tafamasi (Ndwedwe Ward 18, ZA): https://maps.google.com/?q=-29.534163,30.863337', 0.71, FALSE),
  (-29.554718, 30.722748, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.554718,30.722748', 0.59, FALSE),
  (-29.36768, 31.263794, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.367680,31.263794', 0.59, FALSE),
  (-29.087479, 30.967175, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.087479,30.967175', 0.59, FALSE),
  (-29.512392, 30.938429, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.512392,30.938429', 0.59, FALSE),
  (-29.368034, 31.265463, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.368034,31.265463', 0.59, FALSE),
  (-29.082895, 30.974215, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.082895,30.974215', 0.59, FALSE),
  (-29.553665, 30.732933, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.553665,30.732933', 0.59, FALSE),
  (-29.390591, 31.278406, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.390591,31.278406', 0.59, FALSE),
  (-29.325716, 30.918652, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.325716,30.918652', 0.59, FALSE),
  (-29.310501, 30.904789, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.310501,30.904789', 0.59, FALSE),
  (-29.548235, 30.736683, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.548235,30.736683', 0.59, FALSE),
  (-29.090115, 30.968334, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.090115,30.968334', 0.59, FALSE),
  (-29.516945, 30.943012, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.516945,30.943012', 0.59, FALSE),
  (-29.320501, 30.925865, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.320501,30.925865', 0.59, FALSE),
  (-29.516626, 30.940378, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.516626,30.940378', 0.59, FALSE),
  (-29.095108, 30.966169, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.095108,30.966169', 0.59, FALSE),
  (-29.391529, 31.275631, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.391529,31.275631', 0.59, FALSE),
  (-29.390348, 31.271578, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.390348,31.271578', 0.59, FALSE),
  (-29.388069, 31.274176, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.388069,31.274176', 0.59, FALSE),
  (-29.186769, 31.398876, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.186769,31.398876', 0.59, FALSE),
  (-29.387966, 31.274454, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.387966,31.274454', 0.59, FALSE),
  (-29.181435, 31.482931, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.181435,31.482931', 0.59, FALSE),
  (-29.170671, 31.205919, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.170671,31.205919', 0.59, FALSE),
  (-29.303829, 30.902092, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.303829,30.902092', 0.59, FALSE),
  (-29.386189, 31.273716, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.386189,31.273716', 0.59, FALSE),
  (-29.324646, 31.260031, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.324646,31.260031', 0.59, FALSE),
  (-29.09091, 31.427122, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.090910,31.427122', 0.59, FALSE),
  (-29.464512, 30.867273, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.464512,30.867273', 0.59, FALSE),
  (-29.38599, 31.275091, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.385990,31.275091', 0.59, FALSE),
  (-29.325224, 31.260906, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.325224,31.260906', 0.59, FALSE),
  (-29.50362, 31.200943, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.503620,31.200943', 0.59, FALSE),
  (-29.297012, 30.91305, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.297012,30.913050', 0.59, FALSE),
  (-29.457167, 30.865019, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.457167,30.865019', 0.59, FALSE),
  (-29.129314, 31.080215, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.129314,31.080215', 0.59, FALSE),
  (-29.281324, 31.130875, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.281324,31.130875', 0.59, FALSE),
  (-29.122248, 31.084507, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.122248,31.084507', 0.59, FALSE),
  (-29.291508, 30.915297, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.291508,30.915297', 0.59, FALSE),
  (-29.173113, 31.203623, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.173113,31.203623', 0.59, FALSE),
  (-29.363117, 31.26973, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.363117,31.269730', 0.59, FALSE),
  (-29.345985, 30.90609, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.345985,30.906090', 0.59, FALSE),
  (-29.162989, 31.082766, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.162989,31.082766', 0.59, FALSE),
  (-29.16324, 31.087072, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.163240,31.087072', 0.59, FALSE),
  (-29.179375, 31.512911, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.179375,31.512911', 0.59, FALSE),
  (-29.417093, 30.835184, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.417093,30.835184', 0.59, FALSE),
  (-29.477478, 31.108042, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.477478,31.108042', 0.59, FALSE),
  (-29.40877, 30.844627, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.408770,30.844627', 0.59, FALSE),
  (-29.301336, 31.048964, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.301336,31.048964', 0.59, FALSE),
  (-29.469828, 30.955757, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.469828,30.955757', 0.59, FALSE),
  (-29.162245, 31.087847, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.162245,31.087847', 0.59, FALSE),
  (-29.152143, 31.068993, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.152143,31.068993', 0.59, FALSE),
  (-29.276638, 31.057842, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.276638,31.057842', 0.59, FALSE),
  (-29.401474, 31.282833, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.401474,31.282833', 0.59, FALSE),
  (-29.160769, 31.089706, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.160769,31.089706', 0.59, FALSE),
  (-29.34339, 30.886711, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.343390,30.886711', 0.59, FALSE),
  (-29.372704, 30.884005, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.372704,30.884005', 0.59, FALSE),
  (-29.362196, 31.257128, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.362196,31.257128', 0.59, FALSE),
  (-29.372141, 30.883612, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.372141,30.883612', 0.59, FALSE),
  (-29.407707, 31.257961, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.407707,31.257961', 0.59, FALSE),
  (-28.917351, 31.017548, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-28.917351,31.017548', 0.59, FALSE),
  (-29.274712, 31.056988, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.274712,31.056988', 0.59, FALSE),
  (-29.187853, 31.514496, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.187853,31.514496', 0.59, FALSE),
  (-29.341299, 30.888775, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.341299,30.888775', 0.59, FALSE),
  (-29.531672, 30.745712, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.531672,30.745712', 0.59, FALSE),
  (-29.274803, 31.052588, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.274803,31.052588', 0.59, FALSE),
  (-29.337606, 30.891512, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.337606,30.891512', 0.59, FALSE),
  (-29.339146, 31.257011, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.339146,31.257011', 0.59, FALSE),
  (-29.211138, 31.151882, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.211138,31.151882', 0.59, FALSE),
  (-29.590294, 31.005392, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.590294,31.005392', 0.59, FALSE),
  (-29.591063, 31.004177, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.591063,31.004177', 0.59, FALSE),
  (-29.34642, 30.92627, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.346420,30.926270', 0.59, FALSE),
  (-29.302036, 31.080782, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.302036,31.080782 | [2026/03/11, 11:24:13] Dolly YMS District Coord: I sent the email <attached: 00003153-PHOTO-2026-03-11-11-24-13.jpg>', 0.59, FALSE),
  (-29.389217, 30.929829, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.389217,30.929829', 0.59, FALSE),
  (-28.949671, 30.943916, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-28.949671,30.943916', 0.59, FALSE),
  (-29.211117, 31.152008, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.211117,31.152008', 0.59, FALSE),
  (-29.091093, 31.427021, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.091093,31.427021', 0.59, FALSE),
  (-29.448471, 30.813948, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.448471,30.813948', 0.59, FALSE),
  (-29.096569, 31.424374, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.096569,31.424374', 0.59, FALSE),
  (-29.316799, 30.96645, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.316799,30.966450', 0.59, FALSE),
  (-29.097496, 31.421841, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.097496,31.421841', 0.59, FALSE),
  (-29.518845, 31.031698, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.518845,31.031698', 0.59, FALSE),
  (-29.558304, 30.895784, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.558304,30.895784', 0.59, FALSE),
  (-29.293388, 30.894953, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.293388,30.894953', 0.59, FALSE),
  (-29.520098, 31.016083, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.520098,31.016083', 0.59, FALSE),
  (-29.294252, 30.905397, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.294252,30.905397', 0.59, FALSE),
  (-29.531309, 31.008289, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.531309,31.008289', 0.59, FALSE),
  (-29.580202, 30.974947, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.580202,30.974947', 0.59, FALSE),
  (-29.120583, 31.392477, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.120583,31.392477', 0.59, FALSE),
  (-29.186565, 31.398682, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.186565,31.398682', 0.59, FALSE),
  (-29.373865, 30.883204, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.373865,30.883204', 0.59, FALSE),
  (-28.9126, 31.01524, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-28.912600,31.015240', 0.59, FALSE),
  (-29.530479, 31.070799, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.530479,31.070799', 0.59, FALSE),
  (-29.121765, 31.395329, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.121765,31.395329', 0.59, FALSE),
  (-29.110607, 31.027901, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.110607,31.027901', 0.59, FALSE),
  (-29.318367, 30.896994, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.318367,30.896994', 0.59, FALSE),
  (-29.336555, 30.955647, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.336555,30.955647', 0.59, FALSE),
  (-29.597366, 30.8743, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.597366,30.874300', 0.59, FALSE),
  (-29.343395, 30.965652, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.343395,30.965652', 0.59, FALSE),
  (-29.277113, 30.924543, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.277113,30.924543', 0.59, FALSE),
  (-29.43895, 30.812742, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.438950,30.812742', 0.59, FALSE),
  (-29.174019, 31.195818, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.174019,31.195818', 0.59, FALSE),
  (-29.335695, 30.987324, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.335695,30.987324', 0.59, FALSE),
  (-29.330851, 30.983767, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.330851,30.983767', 0.59, FALSE),
  (-29.145744, 31.058434, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.145744,31.058434', 0.59, FALSE),
  (-29.149187, 31.397179, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.149187,31.397179', 0.59, FALSE),
  (-29.327971, 30.985575, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.327971,30.985575', 0.59, FALSE),
  (-29.193392, 31.497139, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.193392,31.497139', 0.59, FALSE),
  (-29.37463, 31.254299, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.374630,31.254299', 0.59, FALSE),
  (-29.18236, 31.191269, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.182360,31.191269', 0.59, FALSE),
  (-29.147976, 31.40019, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.147976,31.400190', 0.59, FALSE),
  (-29.084532, 31.408964, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.084532,31.408964', 0.59, FALSE),
  (-29.573969, 30.855507, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.573969,30.855507', 0.59, FALSE),
  (-29.149874, 31.398153, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.149874,31.398153', 0.59, FALSE),
  (-28.909946, 31.014269, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-28.909946,31.014269', 0.59, FALSE),
  (-29.173624, 31.203732, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.173624,31.203732', 0.59, FALSE),
  (-29.149494, 31.396482, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.149494,31.396482', 0.59, FALSE),
  (-29.086618, 31.40785, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.086618,31.407850', 0.59, FALSE),
  (-29.183235, 31.209179, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.183235,31.209179', 0.59, FALSE),
  (-29.538153, 30.745565, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.538153,30.745565', 0.59, FALSE),
  (-28.91469, 31.004488, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-28.914690,31.004488', 0.59, FALSE),
  (-29.085672, 31.41604, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.085672,31.416040', 0.59, FALSE),
  (-29.191774, 31.394978, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.191774,31.394978', 0.59, FALSE),
  (-29.125734, 31.038979, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.125734,31.038979', 0.59, FALSE),
  (-29.488865, 30.899887, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.488865,30.899887', 0.59, FALSE),
  (-29.087942, 31.008547, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.087942,31.008547', 0.59, FALSE),
  (-29.361666, 30.91724, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.361666,30.917240', 0.59, FALSE),
  (-29.181774, 31.399094, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.181774,31.399094', 0.59, FALSE),
  (-29.360044, 30.923193, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.360044,30.923193', 0.59, FALSE),
  (-29.093784, 31.617254, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.093784,31.617254', 0.59, FALSE),
  (-29.359777, 30.923613, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.359777,30.923613', 0.59, FALSE),
  (-29.092567, 31.00696, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.092567,31.006960', 0.59, FALSE),
  (-29.302446, 31.03249, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.302446,31.032490', 0.59, FALSE),
  (-29.353809, 30.921379, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.353809,30.921379', 0.59, FALSE),
  (-29.093481, 31.006439, 'Location', NULL, NULL, 'Location: https://maps.google.com/?q=-29.093481,31.006439 | [2026/03/26, 11:18:54] Dolly YMS District Coord: kwaCebolethu Store. Maphumulo Ward 05. <attached: 00003312-PHOTO-2026-03-26-11-18-54.jpg>', 0.59, FALSE),
  (-29.542925, 30.867231, 'Jabulile Foundation', NULL, NULL, 'Jabulile Foundation (Thafamasi area, 80221, Ndwedwe Local Municipality, 4342, ZA): https://maps.google.com/?q=-29.542925,30.867231', 0.51, FALSE)
ON CONFLICT DO NOTHING;

-- ── Done ─────────────────────────────────────────────────────────
-- 138 rows seeded from gps_review.csv
-- ============================================================
